Finish making new tests from tsv (spreadsheet) data

diff --git a/bin/tsv-to-new b/bin/tsv-to-new
--- a/bin/tsv-to-new
+++ b/bin/tsv-to-new
@@ -2,6 +2,8 @@
 
 set -e -u -o pipefail
 
+die() { echo "$*" >&2; exit 1; }
+
 root=$(cd "$(dirname "$0")/.." && pwd)
 bin=$root/bin
 
@@ -11,27 +13,45 @@ dir=$root/new
 rm -fr "$dir"
 mkdir "$dir"
 
-from='@ingydotnet'
-# from=$(
-#   perl -e 'print $1 if $ARGV[0] =~ /.*\nHi (\w+)!.*/s' \
-#     "$(ssh git@github.com 2>&1 || true)"
-# )
+if [[ -e .git/githubid ]]; then
+  from=$(< .git/githubid)
+else
+  from=$(
+    ssh git@github.com |&
+      perl -ne '/Hi (\w+)! You/ and print $1'
+  ) || true
+  [[ $from ]] || die "Can't determine github id"
+  from=@$from
+  echo -n "$from" > .git/githubid
+fi
 
-each=()
-while read -r line; do
-  each+=("$line")
-done < <(
-  tsv-to-json < "$tsv" |
-    jq -c '.[]|[(.[1,2,3]),(select(.[0] != "")|true)]'
-)
+mapfile -t each < <(tsv-to-json < "$tsv" | jq -c '.[]')
+mapfile -t head < <(jq -r '.[]' <<<"${each[0]}")
+each=("${each[@]:1}")
+
+# Get all tags. (First tag is 'alias')
+for (( tag_idx = 0; tag_idx < ${#head[*]}; tag_idx++ )); do
+  [[ ${head[tag_idx]} == alias ]] && break
+done
+tag_name=("${head[@]:$tag_idx}")
 
 i=0
 _group=''
 for line in "${each[@]}"; do
-  group=$(jq -r '.[0]' <<<"$line")
-  yaml=$(jq -r '.[1]' <<<"$line")
-  tree=$(jq -r '.[2]' <<<"$line")
-  skip=$(jq -r '.[3] // ""' <<<"$line")
+  yaml=$(jq -r '.[3]' <<<"$line")
+  tree=$(jq -r '.[4]' <<<"$line")
+  mapfile -t cell < <(jq -r ".[1:3],.[5:6],.[$tag_idx:]|.[]" <<<"$line")
+  set -- "${cell[@]}"
+  group=$1; shift
+  name=$1; shift
+  skip=$1; shift
+  tags=()
+  for tag in "${tag_name[@]}"; do
+    if [[ $1 ]]; then
+      tags+=( "$tag" )
+    fi
+    shift
+  done
 
   if [[ $group && $group == $_group ]]; then
     more=1
@@ -45,16 +65,22 @@ for line in "${each[@]}"; do
     _group=$group
   fi
 
-  name=$(printf "%03d-%s" "$i" "$id")
-  file=$dir/$name.yaml
+  file_name=$(printf "%03d-%s" "$i" "$id")
+  file=$dir/$file_name.yaml
 
-  "$bin/yaml-to-test" "$tree" "$from" "$skip" "$more" \
-    <<<"$yaml" >> "$file"
+  YAML="$yaml" \
+  MORE="$more" \
+  SKIP="$skip" \
+  NAME="$name" \
+  FROM="$from" \
+  TAGS="${tags[*]}" \
+  TREE="$tree" \
+  "$bin/yaml-to-test" >> "$file"
 
   if [[ $more ]]; then
     action='  Added to'
   else
     action=Created
   fi
-  echo "$action '$file'"
+  echo "$action 'new/$file_name.yaml'"
 done
